/** @type {import('next').NextConfig} */
const nextConfig = {
  // Three.js is a CJS package — transpile it so Next.js can tree-shake it correctly
  transpilePackages: ['three'],

  images: {
    // Serve AVIF where the browser supports it (smaller than WebP), fall back to WebP.
    // Both are automatically generated by Next.js's image optimisation pipeline.
    // Add your real hero photo to /public/hero-bus.jpg for maximum LCP benefit.
    formats: ['image/avif', 'image/webp'],

    // Breakpoints used to generate srcset variants — covers mobile → large desktop
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },
}

export default nextConfig
