/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    // Serve AVIF where the browser supports it (smaller than WebP), fall back to WebP.
    // Both are automatically generated by Next.js's image optimisation pipeline.
    formats: ['image/avif', 'image/webp'],

    // Breakpoints used to generate srcset variants — covers mobile → large desktop
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],

    remotePatterns: [
      { protocol: 'https', hostname: 'res.cloudinary.com', pathname: '/uwzoaqhg/**' },
    ],
  },
}

export default nextConfig
